spring:
  datasource:
    #内网
    url: jdbc:mysql://rm-j0bt8woy1xl618o5235640.mysql.australia.rds.aliyuncs.com:3306/mee_store?characterEncoding=utf-8
    #外网
    #url: jdbc:mysql://rm-j0bt8woy1xl618o52so.mysql.australia.rds.aliyuncs.com:3306/mee_store?characterEncoding=utf-8
    username: mee_store
    password: AvRYwTFZpmTEdo/5ACiKnwGk6KgXwQSBHoTfeJTOZyWkr69+GuRj7FqmGNL0TjL1MmdnUlOIuFN+MkF0paYEPw==
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

    druid:
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=true;
      initial-size: 5
      min-idle: 5
      max-active: 20
      test-on-borrow: true
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-While-Idle: true
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      filters: config,stat,wall,log4j
      # 配置DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      # 配置DruidStatViewServlet
      stat-view-servlet:
        url-pattern: "/druid/*"
        # IP白名单(没有配置或者为空，则允许所有访问)
        allow:
        # IP黑名单 (存在共同时，deny优先于allow)
        deny: 192.168.1.73
        #  禁用HTML页面上的“Reset All”功能
        reset-enable: false
        # 登录名
        login-username: admin
        # 登录密码
        login-password: 123456
  servlet:
    multipart:
      # 上传一个文件最大值,默认1Mb
      max-file-size: 2MB
      # 上传多个文件最大值,50Mb,默认10Mb
      max-request-size: 2MB
  mail:
    host: smtp.exmail.qq.com
    port: 465
    username: info@heatpumpsnz.com
    password: Kx9l4l#S
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true
            required: true
server:
  port: 8888

mee:
  sso: 
    endpoint: oss-ap-southeast-2.aliyuncs.com
    accessKeyId: LTAI4Fog2x2RqYd4ALEnGECj
    accessKeySecret: GsypppkMg489K6ex6ul5M1ZAKXL0iO
    bucketName: mee-store
    imgUrl: //mee-store.oss-ap-southeast-2.aliyuncs.com
  #addressFile: C:/Users/BBbir/Downloads/lds-nz-street-address-CSV/nz-street-address.csv
  addressFile: /data/nz-street-address.csv
mybatis-plus:
  configuration:
    mapUnderscoreToCamelCase: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
